# Generated by Django 5.2.15 on 2026-06-23 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='last_webhook_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
