# Generated by Django 6.0.6 on 2026-06-25 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_profile_last_webhook_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='inaturalist_user_id',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
