# Generated by Django 6.0.6 on 2026-06-26 05:18

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_profile_inaturalist_user_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityRecheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_id', models.BigIntegerField()),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('tier', models.PositiveSmallIntegerField(default=0)),
                ('due_at', models.DateTimeField(db_index=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.profile')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('profile', 'activity_id'), name='uniq_pending_recheck')],
            },
        ),
    ]
