import re
from .timespan import IdDates

# The bird block is delimited by a human-readable header and footer (Strava
# descriptions are plain text, so HTML-comment markers would show literally).
# The footer doubles as the attribution line and the end delimiter used to
# find-and-replace the block on re-sync.
BLOCK_HEADER = "Nature seen during activity:"
BLOCK_FOOTER = "Generated by Roadrunner"
# Strava auto-links bare URLs (it doesn't support anchor text/HTML/Markdown), so
# the footer carries the raw app URL on its own line to make it clickable.
ROADRUNNER_URL = "https://roadrunner-iota-nine.vercel.app/"
# Match header..footer plus an optional trailing URL line, so re-sync replaces the
# whole block cleanly even if the URL changes.
_BLOCK_RE = re.compile(
    r"(?:Birds|Nature) seen during activity:" + r".*?"
    + re.escape(BLOCK_FOOTER) + r"(?:\n\S+)?",
    re.DOTALL,
)


def compare(a: IdDates, b: IdDates) -> bool:
    latest_start = max(a.start_date, b.start_date)
    earliest_end = min(a.end_date, b.end_date)
    return earliest_end > latest_start


def add_dict(current: dict, new: dict) -> dict:
    merged = current.copy()
    for k, v in new.items():
        if k not in merged:
            merged[k] = v
        elif not v:                                   # iNat has no count — keep existing
            continue
        elif not merged[k]:                           # existing had no count — take the count
            merged[k] = v
        elif v.isnumeric() and merged[k].isnumeric():
            merged[k] = str(int(v) + int(merged[k]))
        else:
            merged[k] = "X"
    return merged


def create_bird_description(species_num: dict) -> str:
    return "".join(
        f"{value} {key}\n" if value else f"{key}\n"
        for key, value in species_num.items()
    )


def upsert_block(description: str | None, bird_list: str) -> str:
    description = description or ""
    block = f"{BLOCK_HEADER}\n{bird_list.rstrip()}\n\n{BLOCK_FOOTER}\n{ROADRUNNER_URL}"
    if _BLOCK_RE.search(description):
        # lambda replacement so bird names with backslashes can't be read as
        # regex group references.
        return _BLOCK_RE.sub(lambda _m: block, description)
    if description.strip():
        return f"{description.rstrip()}\n\n{block}"
    return block
